---
name: "Build"
on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: |
          make

      - uses: actions/upload-artifact@v3
        with:
          name: tarball
          path: |
            dist/bluehat.tar.gz

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/bluehat.tar.gz
